# Generated by Django 5.0.4 on 2024-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
