# Generated by Django 5.0.4 on 2024-05-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, max_length=400)),
                ('thumbnail', models.ImageField(upload_to='tutorialpic')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
            ],
            options={
                'verbose_name': 'tutorial',
                'verbose_name_plural': 'tutorial',
            },
        ),
    ]
