# Generated by Django 5.0.4 on 2024-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
